import { ResumeData } from "./types";

export const RESUME_TEMPLATES: Record<string, ResumeData> = {
    "software-developer": {
        personalInfo: {
            fullName: "Alex Johnson",
            email: "alex.johnson@example.com",
            phone: "+1 (555) 123-4567",
            address: "San Francisco, CA",
            linkedin: "linkedin.com/in/alexjohnson",
            website: "github.com/alexjohnson",
            summary: "Passionate Software Developer with 3+ years of experience in building scalable web applications. Proficient in JavaScript, React, and Node.js. Dedicated to writing clean, maintainable code and solving complex problems.",
        },
        experience: [
            {
                id: "1",
                company: "Tech Solutions Inc.",
                position: "Software Developer",
                startDate: "01/2022",
                endDate: "Present",
                current: true,
                description: "• Developed and maintained customer-facing web applications using React and TypeScript.\n• Collaborated with UX/UI designers to implement responsive and accessible interfaces.\n• Optimized application performance, reducing load times by 30%.",
            },
            {
                id: "2",
                company: "StartUp Co.",
                position: "Junior Developer",
                startDate: "06/2020",
                endDate: "12/2021",
                current: false,
                description: "• Assisted in the development of a RESTful API using Node.js and Express.\n• Wrote unit and integration tests to ensure code quality.\n• Participated in code reviews and agile ceremonies.",
            },
        ],
        education: [
            {
                id: "1",
                institution: "State University",
                degree: "BS",
                field: "Computer Science",
                startDate: "2016",
                endDate: "2020",
                current: false,
                description: "",
            },
        ],
        skills: [
            { id: "1", name: "JavaScript", level: "Expert" },
            { id: "2", name: "React", level: "Advanced" },
            { id: "3", name: "Node.js", level: "Intermediate" },
            { id: "4", name: "TypeScript", level: "Advanced" },
        ],
        projects: [
            {
                id: "1",
                name: "E-commerce Platform",
                description: "Built a full-featured e-commerce site with cart and payment integration.",
                link: "github.com/alexjohnson/ecommerce",
            },
        ],
        achievements: [],
    },
    "frontend-developer": {
        personalInfo: {
            fullName: "Sarah Lee",
            email: "sarah.lee@example.com",
            phone: "+1 (555) 987-6543",
            address: "New York, NY",
            linkedin: "linkedin.com/in/sarahlee",
            website: "sarahlee.dev",
            summary: "Creative Frontend Developer with a keen eye for design and detail. Expert in React, Vue.js, and modern CSS frameworks. Committed to creating engaging user experiences.",
        },
        experience: [
            {
                id: "1",
                company: "Creative Agency",
                position: "Frontend Developer",
                startDate: "03/2021",
                endDate: "Present",
                current: true,
                description: "• Built pixel-perfect responsive websites for diverse clients.\n• Implemented complex animations using GSAP and Framer Motion.\n• Ensured cross-browser compatibility and accessibility compliance.",
            },
        ],
        education: [
            {
                id: "1",
                institution: "Art Institute",
                degree: "BA",
                field: "Interaction Design",
                startDate: "2017",
                endDate: "2021",
                current: false,
                description: "",
            },
        ],
        skills: [
            { id: "1", name: "React", level: "Expert" },
            { id: "2", name: "Vue.js", level: "Advanced" },
            { id: "3", name: "CSS/Tailwind", level: "Expert" },
        ],
        projects: [],
        achievements: [],
    },
    "backend-developer": {
        personalInfo: {
            fullName: "Michael Chen",
            email: "michael.chen@example.com",
            phone: "+1 (555) 456-7890",
            address: "Seattle, WA",
            linkedin: "linkedin.com/in/michaelchen",
            website: "github.com/michaelchen",
            summary: "Backend Developer specializing in building robust and scalable server-side applications. Experienced with Python, Django, and PostgreSQL. Strong problem-solving skills and database design knowledge.",
        },
        experience: [
            {
                id: "1",
                company: "Cloud Systems",
                position: "Backend Engineer",
                startDate: "08/2020",
                endDate: "Present",
                current: true,
                description: "• Designed and implemented microservices architecture using Python and Flask.\n• Managed high-availability PostgreSQL databases.\n• Integrated third-party APIs for payment processing and messaging.",
            },
        ],
        education: [
            {
                id: "1",
                institution: "Tech University",
                degree: "MS",
                field: "Software Engineering",
                startDate: "2018",
                endDate: "2020",
                current: false,
                description: "",
            },
        ],
        skills: [
            { id: "1", name: "Python", level: "Expert" },
            { id: "2", name: "Django", level: "Advanced" },
            { id: "3", name: "PostgreSQL", level: "Advanced" },
            { id: "4", name: "Docker", level: "Intermediate" },
        ],
        projects: [],
        achievements: [],
    },
    "fullstack-developer": {
        personalInfo: {
            fullName: "Emily Davis",
            email: "emily.davis@example.com",
            phone: "+1 (555) 789-0123",
            address: "Austin, TX",
            linkedin: "linkedin.com/in/emilydavis",
            website: "emilydavis.io",
            summary: "Versatile Full-Stack Developer proficient in the MERN stack. Capable of handling both frontend UI and backend logic. Passionate about building complete web solutions from scratch.",
        },
        experience: [],
        education: [],
        skills: [
            { id: "1", name: "MongoDB", level: "Advanced" },
            { id: "2", name: "Express", level: "Advanced" },
            { id: "3", name: "React", level: "Advanced" },
            { id: "4", name: "Node.js", level: "Advanced" },
        ],
        projects: [],
        achievements: [],
    },
    "mobile-developer": {
        personalInfo: {
            fullName: "David Wilson",
            email: "david.wilson@example.com",
            phone: "+1 (555) 321-6549",
            address: "Denver, CO",
            linkedin: "linkedin.com/in/davidwilson",
            website: "",
            summary: "Mobile App Developer with experience in React Native and Swift. Published multiple apps to the App Store and Google Play. Focused on creating smooth, native-like mobile experiences.",
        },
        experience: [],
        education: [],
        skills: [
            { id: "1", name: "React Native", level: "Advanced" },
            { id: "2", name: "Swift", level: "Intermediate" },
            { id: "3", name: "Firebase", level: "Intermediate" },
        ],
        projects: [],
        achievements: [],
    },
    "qa-engineer": {
        personalInfo: {
            fullName: "Jennifer Brown",
            email: "jennifer.brown@example.com",
            phone: "+1 (555) 654-3210",
            address: "Boston, MA",
            linkedin: "linkedin.com/in/jenniferbrown",
            website: "",
            summary: "Detail-oriented QA Engineer with experience in manual and automated testing. Skilled in Selenium, Cypress, and writing test plans. Ensures high standards of software quality.",
        },
        experience: [],
        education: [],
        skills: [
            { id: "1", name: "Selenium", level: "Advanced" },
            { id: "2", name: "Cypress", level: "Intermediate" },
            { id: "3", name: "JIRA", level: "Advanced" },
        ],
        projects: [],
        achievements: [],
    },
    "devops-engineer": {
        personalInfo: {
            fullName: "Robert Taylor",
            email: "robert.taylor@example.com",
            phone: "+1 (555) 147-2583",
            address: "Chicago, IL",
            linkedin: "linkedin.com/in/roberttaylor",
            website: "",
            summary: "DevOps Engineer with expertise in CI/CD pipelines, cloud infrastructure (AWS), and containerization. Focused on automating deployment processes and improving system reliability.",
        },
        experience: [],
        education: [],
        skills: [
            { id: "1", name: "AWS", level: "Advanced" },
            { id: "2", name: "Docker", level: "Advanced" },
            { id: "3", name: "Kubernetes", level: "Intermediate" },
            { id: "4", name: "Jenkins", level: "Advanced" },
        ],
        projects: [],
        achievements: [],
    },
    "data-scientist": {
        personalInfo: {
            fullName: "Dr. Amanda White",
            email: "amanda.white@example.com",
            phone: "+1 (555) 963-8521",
            address: "Palo Alto, CA",
            linkedin: "linkedin.com/in/amandawhite",
            website: "amand DataScience.com",
            summary: "Data Scientist with a Ph.D. in Statistics. Experienced in machine learning, statistical modeling, and data visualization. Skilled in Python, R, and TensorFlow. Turns data into actionable insights.",
        },
        experience: [],
        education: [],
        skills: [
            { id: "1", name: "Python", level: "Expert" },
            { id: "2", name: "Machine Learning", level: "Expert" },
            { id: "3", name: "TensorFlow", level: "Advanced" },
            { id: "4", name: "SQL", level: "Advanced" },
        ],
        projects: [],
        achievements: [],
    },
    "data-analyst": {
        personalInfo: {
            fullName: "James Anderson",
            email: "james.anderson@example.com",
            phone: "+1 (555) 741-8529",
            address: "New York, NY",
            linkedin: "linkedin.com/in/jamesanderson",
            website: "",
            summary: "Analytical Data Analyst with strong SQL and Excel skills. Experienced in creating dashboards with Tableau and Power BI. passionate about uncovering trends and patterns in data.",
        },
        experience: [],
        education: [],
        skills: [
            { id: "1", name: "SQL", level: "Advanced" },
            { id: "2", name: "Excel", level: "Expert" },
            { id: "3", name: "Tableau", level: "Advanced" },
            { id: "4", name: "Power BI", level: "Advanced" },
        ],
        projects: [],
        achievements: [],
    },
    "database-administrator": {
        personalInfo: {
            fullName: "Patricia Martinez",
            email: "patricia.martinez@example.com",
            phone: "+1 (555) 852-9637",
            address: "Dallas, TX",
            linkedin: "linkedin.com/in/patriciamartinez",
            website: "",
            summary: "Experienced Database Administrator managing Oracle and MySQL databases. Skilled in performance tuning, backup and recovery, and security management. Ensures data integrity and availability.",
        },
        experience: [],
        education: [],
        skills: [
            { id: "1", name: "Oracle DB", level: "Expert" },
            { id: "2", name: "MySQL", level: "Advanced" },
            { id: "3", name: "Linux", level: "Advanced" },
        ],
        projects: [],
        achievements: [],
    },
    "data-architect": {
        personalInfo: {
            fullName: "Thomas Moore",
            email: "thomas.moore@example.com",
            phone: "+1 (555) 369-1478",
            address: "Seattle, WA",
            linkedin: "linkedin.com/in/thomasmoore",
            website: "",
            summary: "Data Architect designing scalable data solutions for enterprise applications. Expert in data modeling, ETL processes, and big data technologies. Translates business requirements into technical blueprints.",
        },
        experience: [],
        education: [],
        skills: [
            { id: "1", name: "Data Modeling", level: "Expert" },
            { id: "2", name: "ETL", level: "Advanced" },
            { id: "3", name: "Hadoop", level: "Intermediate" },
            { id: "4", name: "Spark", level: "Intermediate" },
        ],
        projects: [],
        achievements: [],
    }
};
